# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:
        enabled: true
    allowed_methods_listener:
        enabled: true
    routing_loader: true
    view:
        view_response_listener: true
#    exception:
#        codes:
#            App\Exception\MyException: '403'
#        messages:
#            App\Exception\MyException: 'Forbidden area.'
#    format_listener:
#        enabled: true
#        rules:
#            - { path: '^/api', prefer_extension: true, fallback_format: 'html', priorities: [ 'json', 'twig', 'html' ] }
