parameters:
    app.path.post_images: /uploads/images/post

vich_uploader:
    db_driver: orm

    mappings:
        post_image:
            uri_prefix: '%app.path.post_images%'
            upload_destination: '%kernel.project_dir%/public/uploads/images/post'